/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;

import com.jlu.magmalab.dao.tables.ApplyInfo;
import com.jlu.magmalab.dao.tables.TmUser;


/**
 * A class modelling indexes of tables of the <code>system</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APPLY_INFO_PRIMARY = Indexes0.APPLY_INFO_PRIMARY;
    public static final Index TM_USER_PRIMARY = Indexes0.TM_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index APPLY_INFO_PRIMARY = createIndex("PRIMARY", ApplyInfo.APPLY_INFO, new OrderField[] { ApplyInfo.APPLY_INFO.APPLY_ID }, true);
        public static Index TM_USER_PRIMARY = createIndex("PRIMARY", TmUser.TM_USER, new OrderField[] { TmUser.TM_USER.USER_ID }, true);
    }
}
