/*
 * This file is generated by jOOQ.
*/
package com.jlu.magmalab.dao;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import com.jlu.magmalab.dao.tables.ApplyInfo;
import com.jlu.magmalab.dao.tables.TmUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class System extends SchemaImpl {

    private static final long serialVersionUID = -2032168103;

    /**
     * The reference instance of <code>system</code>
     */
    public static final System SYSTEM = new System();

    /**
     * The table <code>system.apply_info</code>.
     */
    public final ApplyInfo APPLY_INFO = com.jlu.magmalab.dao.tables.ApplyInfo.APPLY_INFO;

    /**
     * The table <code>system.tm_user</code>.
     */
    public final TmUser TM_USER = com.jlu.magmalab.dao.tables.TmUser.TM_USER;

    /**
     * No further instances allowed
     */
    private System() {
        super("system", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ApplyInfo.APPLY_INFO,
            TmUser.TM_USER);
    }
}
